---
- name: "Execute the Ansible Tower backup"
  shell: "./setup.sh -b"
  args:
    chdir: "{{ ansible_tower_directory }}"

- name: "Copy backup file to a remote file server"
  copy:
    remote_src: yes
    src: "{{ ansible_tower_directory }}/tower-backup-latest.tar.gz"
    dest: "{{ web_dir }}"

- name: "Verify that jobs are not running on the destination tower"
  shell: "while [ $(curl -k -X GET --user {{ tower_username }}:{{ tower_password }} https://10.35.97.152/api/v2/jobs/?status=running -L | jq '.count') -ne 0 ]; do sleep 1; echo 'A job is running - Re-checking'; done"

- name: "Run the restore process from the second tower"
  uri:
    url: "https://10.35.97.152/api/v2/job_templates/restore-tower/launch/"
    validate_certs: no
    method: POST
    return_content: yes
    force_basic_auth: yes
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    status_code: [201, 202]
