---
- name: "Download the restore file from the web"
  get_url:
    url: "{{ backup_web_path }}"
    dest: "{{ ansible_tower_directory }}"

- name: "Install the 'at' CLI"
  yum:
    name: at
    state: present

- name: "Enable th 'atd' service"
  service:
    name: atd
    state: started
    enabled: yes

- name: "Verify that jobs are not running on the destination tower"
  shell: "while [ $(curl -k -X GET --user {{ tower_username }}:{{ tower_password }} https://127.0.0.1/api/v2/jobs/?status=running -L | jq '.count') -ne 1 ]; do sleep 1; echo 'A job is running - Re-checking'; done"

- name: "Schedule the restore to run in 1 minute"
  at:
    command: "sh {{ ansible_tower_directory }}/setup.sh -r"
    count: 1
    units: minutes
